package com.personal.multiregion.model;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.io.Serializable;

@DynamoDBTable(tableName = "assignment")
public class Assignment implements Serializable {

    private static final long serialVersionUID = 1L;

    private String assignmentId;
    private String userId;
    private String externalAssignmentId;
    boolean isActive;
    boolean isCompleted;
    boolean isCreated;

    @DynamoDBHashKey(attributeName = "assignmentId")
    @DynamoDBAutoGeneratedKey
    public String getAssignmentId() {
        return assignmentId;
    }

    public void setAssignmentId(String assignmentId) {
        this.assignmentId = assignmentId;
    }

    @DynamoDBRangeKey
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    @DynamoDBAttribute
    public String getExternalAssignmentId() {
        return externalAssignmentId;
    }

    public void setExternalAssignmentId(String externalAssignmentId) {
        this.externalAssignmentId = externalAssignmentId;
    }

    @DynamoDBAttribute
    public boolean isActive() {
        return isActive;
    }

    public void setActive(boolean active) {
        isActive = active;
    }

    @DynamoDBAttribute
    public boolean isCompleted() {
        return isCompleted;
    }

    public void setCompleted(boolean completed) {
        isCompleted = completed;
    }

    @DynamoDBAttribute
    public boolean isCreated() {
        return isCreated;
    }

    public void setCreated(boolean created) {
        isCreated = created;
    }
}
